In [1]:
import pandas as pd

In [2]:
filename = "C:\\Users\\Admin\\Downloads\\Inside Sales Funnel  - ISRDetails.xlsx"
df1 = pd.read_excel(filename)

In [3]:
df = pd.DataFrame(df1)

In [4]:
df.head()

,Domain,Company,Email Month,Inside Sales\nConnect\nStage,Sales Qualification Stage,Sales Qualification Reason,Qual Month,Lead Owner,Contact- Designation- Phone Number,Email,Remarks by insight sales
0,privatecircle.co,Private Circle,Sep,Meeting,Qualified,NaN,Sep,Sid,Krishna Skc Founder- 9940398894,krishna@privatecircle.co,Acc to Sid I just spoke to Vansh of Private Ci...
1,blockonomics.co,Blockonomics,Sep,Meeting,DisQualified,Laterals,NaN,Anirudh,shiva sitamraju (Founder & CEO) +919704534662,shiva@blockonomics.co,They Small company currently they are looking ...
2,ssbsoft.com,SSB software,Sep,Meeting,DisQualified,Budget,NaN,Sid,Magalingam Jayagopal (Founder & CEO)- 9940122555,mali@ssbsoft.com,They have issue with the budget
3,girmiti.com,Girmiti,Sep,Meeting,DisQualified,Tech Stack Mismatch,NaN,Anirudh,Deric John\n Recruiting Manager\n Mob: +91-988...,deric.john@girmiti.com,They are on tech that we don't support.
4,hipbar.com,Hipbar,Sep,Meeting,DisQualified,Timeline,NaN,Sid,Prasanna Natarajan (Founder),pras@hipbar.com,"Acc to Sid, the HR says their requirement are ..."

In [5]:
Filename1='C:\\Users\\Admin\\Company.csv'
data = pd.read_csv(Filename1)

In [6]:
data = pd.DataFrame(data)

In [7]:
data.head()

,Unnamed: 0,Domain,Company,Segment,Week,VC,Lead Owner,Location,Region,id_co
0,0,shuttl.com,Shuttl,X,w38,X,Shubham,NCR,North,SNX0
1,1,godigit.com,Digit Insurance,X,w38,X,Rozer,Bengaluru,South,DBX1
2,2,swiggy.in,Swiggy,X,w38,X,Shubham,Bengaluru,South,SBX2
3,3,cleardekho.com,Cleardekho,X,w38,X,Shubham,NCR,North,CNX3
4,4,zomato.com,Zomato,X,w38,X,Shubham,NCR,North,ZNX4

In [8]:
data = data[['Domain', 'id_co']]

In [9]:
data.head()

           Domain id_co
0      shuttl.com  SNX0
1     godigit.com  DBX1
2       swiggy.in  SBX2
3  cleardekho.com  CNX3
4      zomato.com  ZNX4

In [10]:
x = df.merge(data, left_on = 'Domain', right_on = 'Domain')

In [11]:
x.head()

,Domain,Company,Email Month,Inside Sales\nConnect\nStage,Sales Qualification Stage,Sales Qualification Reason,Qual Month,Lead Owner,Contact- Designation- Phone Number,Email,Remarks by insight sales,id_co
0,privatecircle.co,Private Circle,Sep,Meeting,Qualified,NaN,Sep,Sid,Krishna Skc Founder- 9940398894,krishna@privatecircle.co,Acc to Sid I just spoke to Vansh of Private Ci...,PBP3616
1,blockonomics.co,Blockonomics,Sep,Meeting,DisQualified,Laterals,NaN,Anirudh,shiva sitamraju (Founder & CEO) +919704534662,shiva@blockonomics.co,They Small company currently they are looking ...,BHF3138
2,ssbsoft.com,SSB software,Sep,Meeting,DisQualified,Budget,NaN,Sid,Magalingam Jayagopal (Founder & CEO)- 9940122555,mali@ssbsoft.com,They have issue with the budget,SCM3700
3,girmiti.com,Girmiti,Sep,Meeting,DisQualified,Tech Stack Mismatch,NaN,Anirudh,Deric John\n Recruiting Manager\n Mob: +91-988...,deric.john@girmiti.com,They are on tech that we don't support.,GBX1018
4,girmiti.com,Girmiti Software,July,Call,DisQualified,Budget,NaN,Sid,Sajesh Babu| Associate AVP | +91 9986017324,sajesh.babu@girmiti.com,Not interested. Budget too high for candidates...,GBX1018

In [12]:
Filename1='C:\\Users\\Admin\\IS_Funnel.csv'

In [13]:
IS_Funnel = x.to_csv(Filename1)